### ISSUE TITLE
Add build server

### ISSUE THREAD

**Issue by steenhulthin** [theaob/wpXml2Jekyll#11]
It would be really useful to have a build server for the project. I suggest to use [appveyor](http://www.appveyor.com/) which is free for open source projects. In my opinion it is very easy to set up.

**Comment by theaob** [comment]
I didn't know about appveyor. Its super easy to set up. I added CI badge to readme.

**Comment by steenhulthin** [comment]
Jep. For .net it's less work than for instance travis-ci.
