### ISSUE TITLE
support Chinese or else

### ISSUE THREAD

**Issue by xiangzhuyuan** [theaob/wpXml2Jekyll#6]
Hi, thanks for your work. when I use it to convert my wordpress exported xml to single post file, my post title change into Mojibake(http://en.wikipedia.org/wiki/Mojibake), I think it would be better when make a steamreader, you can point out your encoding.

'''C sharp
StreamReader sr = new StreamReader(filename,Encoding.GetEncoding("utf-8"));
'''

**Comment by theaob** [comment]
Thanks for your interest.
I currently have no PC with Visual Studio installed, so either you can post a pull request or wait for a few weeks.

**Comment by theaob** [comment]
made some changes, please check it out so I can close this issue

**Comment by xiangzhuyuan** [comment]
Hi, thanks for your response. I have also no .net development environment. it's so big. I check it, it's ok. thanks. you can close this issue.
